//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamUp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamUp.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This page is under construction.
        /// </summary>
        internal static string DevPage1 {
            get {
                return ResourceManager.GetString("DevPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stay tuned for futher updates.
        /// </summary>
        internal static string DevPage2 {
            get {
                return ResourceManager.GetString("DevPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back Home.
        /// </summary>
        internal static string DevPage3 {
            get {
                return ResourceManager.GetString("DevPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What&apos;s new?.
        /// </summary>
        internal static string HomeNews1 {
            get {
                return ResourceManager.GetString("HomeNews1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Who to follow?.
        /// </summary>
        internal static string HomeNews2 {
            get {
                return ResourceManager.GetString("HomeNews2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What&apos;s new?.
        /// </summary>
        internal static string HomePosts {
            get {
                return ResourceManager.GetString("HomePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andrew Rudenko.
        /// </summary>
        internal static string HomeProfile1 {
            get {
                return ResourceManager.GetString("HomeProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @andrew_rudenko.
        /// </summary>
        internal static string HomeProfile2 {
            get {
                return ResourceManager.GetString("HomeProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer.
        /// </summary>
        internal static string HomeProfile3 {
            get {
                return ResourceManager.GetString("HomeProfile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        internal static string Languages1 {
            get {
                return ResourceManager.GetString("Languages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select language that best suits you.
        /// </summary>
        internal static string Languages2 {
            get {
                return ResourceManager.GetString("Languages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string Languages3 {
            get {
                return ResourceManager.GetString("Languages3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deutsch.
        /// </summary>
        internal static string Languages4 {
            get {
                return ResourceManager.GetString("Languages4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string Languages5 {
            get {
                return ResourceManager.GetString("Languages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posts.
        /// </summary>
        internal static string MainData1 {
            get {
                return ResourceManager.GetString("MainData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Media.
        /// </summary>
        internal static string MainData2 {
            get {
                return ResourceManager.GetString("MainData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects.
        /// </summary>
        internal static string MainData3 {
            get {
                return ResourceManager.GetString("MainData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CV.
        /// </summary>
        internal static string MainData4 {
            get {
                return ResourceManager.GetString("MainData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string MainMenu1 {
            get {
                return ResourceManager.GetString("MainMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages.
        /// </summary>
        internal static string MainMenu2 {
            get {
                return ResourceManager.GetString("MainMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification.
        /// </summary>
        internal static string MainMenu3 {
            get {
                return ResourceManager.GetString("MainMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        internal static string MainMenu4 {
            get {
                return ResourceManager.GetString("MainMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work.
        /// </summary>
        internal static string MainMenu5 {
            get {
                return ResourceManager.GetString("MainMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string MainMenu6 {
            get {
                return ResourceManager.GetString("MainMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andrew Rudenko.
        /// </summary>
        internal static string MainProfile1 {
            get {
                return ResourceManager.GetString("MainProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @andrew_rudenko.
        /// </summary>
        internal static string MainProfile2 {
            get {
                return ResourceManager.GetString("MainProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukraine, Odessa.
        /// </summary>
        internal static string MainProfile3 {
            get {
                return ResourceManager.GetString("MainProfile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Born October 1, 2002.
        /// </summary>
        internal static string MainProfile4 {
            get {
                return ResourceManager.GetString("MainProfile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact Info.
        /// </summary>
        internal static string MainProfile5 {
            get {
                return ResourceManager.GetString("MainProfile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Profile.
        /// </summary>
        internal static string MainProfile6 {
            get {
                return ResourceManager.GetString("MainProfile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        internal static string Notifications1 {
            get {
                return ResourceManager.GetString("Notifications1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable notifications.
        /// </summary>
        internal static string Notifications2 {
            get {
                return ResourceManager.GetString("Notifications2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preference.
        /// </summary>
        internal static string Notifications3 {
            get {
                return ResourceManager.GetString("Notifications3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Likes.
        /// </summary>
        internal static string Notifications4 {
            get {
                return ResourceManager.GetString("Notifications4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friends add.
        /// </summary>
        internal static string Notifications5 {
            get {
                return ResourceManager.GetString("Notifications5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages.
        /// </summary>
        internal static string Notifications6 {
            get {
                return ResourceManager.GetString("Notifications6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Posts.
        /// </summary>
        internal static string Notifications7 {
            get {
                return ResourceManager.GetString("Notifications7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        internal static string Security1 {
            get {
                return ResourceManager.GetString("Security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter old password:.
        /// </summary>
        internal static string Security2 {
            get {
                return ResourceManager.GetString("Security2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new password:.
        /// </summary>
        internal static string Security3 {
            get {
                return ResourceManager.GetString("Security3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Again new password:.
        /// </summary>
        internal static string Security4 {
            get {
                return ResourceManager.GetString("Security4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Security5 {
            get {
                return ResourceManager.GetString("Security5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account .
        /// </summary>
        internal static string Setting1 {
            get {
                return ResourceManager.GetString("Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        internal static string Setting2 {
            get {
                return ResourceManager.GetString("Setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        internal static string Setting3 {
            get {
                return ResourceManager.GetString("Setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        internal static string Setting4 {
            get {
                return ResourceManager.GetString("Setting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log off.
        /// </summary>
        internal static string Setting5 {
            get {
                return ResourceManager.GetString("Setting5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string Setting6 {
            get {
                return ResourceManager.GetString("Setting6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show More.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stay tuned futher updates.
        /// </summary>
        internal static string Stay {
            get {
                return ResourceManager.GetString("Stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать на события.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
