//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamUp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamUp.Localization.", typeof(Localization_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ця сторінка знаходиться у розробці.
        /// </summary>
        internal static string DevPage1 {
            get {
                return ResourceManager.GetString("DevPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слідкуйте за подальшими оновленнями.
        /// </summary>
        internal static string DevPage2 {
            get {
                return ResourceManager.GetString("DevPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернутися додому.
        /// </summary>
        internal static string DevPage3 {
            get {
                return ResourceManager.GetString("DevPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підписка.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Що нового?.
        /// </summary>
        internal static string HomeNews1 {
            get {
                return ResourceManager.GetString("HomeNews1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хто підписався?.
        /// </summary>
        internal static string HomeNews2 {
            get {
                return ResourceManager.GetString("HomeNews2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Що нового?.
        /// </summary>
        internal static string HomePosts {
            get {
                return ResourceManager.GetString("HomePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Андрій Руденко.
        /// </summary>
        internal static string HomeProfile1 {
            get {
                return ResourceManager.GetString("HomeProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @andrew_rudenko.
        /// </summary>
        internal static string HomeProfile2 {
            get {
                return ResourceManager.GetString("HomeProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розробник.
        /// </summary>
        internal static string HomeProfile3 {
            get {
                return ResourceManager.GetString("HomeProfile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мови.
        /// </summary>
        internal static string Languages1 {
            get {
                return ResourceManager.GetString("Languages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виберіть мову, яка вам найбільше підходить.
        /// </summary>
        internal static string Languages2 {
            get {
                return ResourceManager.GetString("Languages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англійська.
        /// </summary>
        internal static string Languages3 {
            get {
                return ResourceManager.GetString("Languages3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Український.
        /// </summary>
        internal static string Languages4 {
            get {
                return ResourceManager.GetString("Languages4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Російська.
        /// </summary>
        internal static string Languages5 {
            get {
                return ResourceManager.GetString("Languages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пости.
        /// </summary>
        internal static string MainData1 {
            get {
                return ResourceManager.GetString("MainData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медіа.
        /// </summary>
        internal static string MainData2 {
            get {
                return ResourceManager.GetString("MainData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекти.
        /// </summary>
        internal static string MainData3 {
            get {
                return ResourceManager.GetString("MainData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CV.
        /// </summary>
        internal static string MainData4 {
            get {
                return ResourceManager.GetString("MainData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додому.
        /// </summary>
        internal static string MainMenu1 {
            get {
                return ResourceManager.GetString("MainMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення.
        /// </summary>
        internal static string MainMenu2 {
            get {
                return ResourceManager.GetString("MainMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення.
        /// </summary>
        internal static string MainMenu3 {
            get {
                return ResourceManager.GetString("MainMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заходи.
        /// </summary>
        internal static string MainMenu4 {
            get {
                return ResourceManager.GetString("MainMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робота.
        /// </summary>
        internal static string MainMenu5 {
            get {
                return ResourceManager.GetString("MainMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        internal static string MainMenu6 {
            get {
                return ResourceManager.GetString("MainMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Андрій Руденко.
        /// </summary>
        internal static string MainProfile1 {
            get {
                return ResourceManager.GetString("MainProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @andrew_rudenko.
        /// </summary>
        internal static string MainProfile2 {
            get {
                return ResourceManager.GetString("MainProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Україна, Одеса.
        /// </summary>
        internal static string MainProfile3 {
            get {
                return ResourceManager.GetString("MainProfile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жовтень 1, 2022.
        /// </summary>
        internal static string MainProfile4 {
            get {
                return ResourceManager.GetString("MainProfile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактна інформація.
        /// </summary>
        internal static string MainProfile5 {
            get {
                return ResourceManager.GetString("MainProfile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити профіль.
        /// </summary>
        internal static string MainProfile6 {
            get {
                return ResourceManager.GetString("MainProfile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення.
        /// </summary>
        internal static string Notifications1 {
            get {
                return ResourceManager.GetString("Notifications1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включити повідомлення.
        /// </summary>
        internal static string Notifications2 {
            get {
                return ResourceManager.GetString("Notifications2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вподобання.
        /// </summary>
        internal static string Notifications3 {
            get {
                return ResourceManager.GetString("Notifications3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лайки.
        /// </summary>
        internal static string Notifications4 {
            get {
                return ResourceManager.GetString("Notifications4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Друзі.
        /// </summary>
        internal static string Notifications5 {
            get {
                return ResourceManager.GetString("Notifications5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения.
        /// </summary>
        internal static string Notifications6 {
            get {
                return ResourceManager.GetString("Notifications6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пости.
        /// </summary>
        internal static string Notifications7 {
            get {
                return ResourceManager.GetString("Notifications7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошта:.
        /// </summary>
        internal static string Security1 {
            get {
                return ResourceManager.GetString("Security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть старий пароль:.
        /// </summary>
        internal static string Security2 {
            get {
                return ResourceManager.GetString("Security2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть новий пароль:.
        /// </summary>
        internal static string Security3 {
            get {
                return ResourceManager.GetString("Security3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть новий пароль ще раз:.
        /// </summary>
        internal static string Security4 {
            get {
                return ResourceManager.GetString("Security4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        internal static string Security5 {
            get {
                return ResourceManager.GetString("Security5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        internal static string Setting1 {
            get {
                return ResourceManager.GetString("Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Захист.
        /// </summary>
        internal static string Setting2 {
            get {
                return ResourceManager.GetString("Setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення.
        /// </summary>
        internal static string Setting3 {
            get {
                return ResourceManager.GetString("Setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова.
        /// </summary>
        internal static string Setting4 {
            get {
                return ResourceManager.GetString("Setting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вийти.
        /// </summary>
        internal static string Setting5 {
            get {
                return ResourceManager.GetString("Setting5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернутися.
        /// </summary>
        internal static string Setting6 {
            get {
                return ResourceManager.GetString("Setting6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Докладніше.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
    }
}
